port=53
listen-address=0.0.0.0
bind-interfaces
user=root
cache-size=1000
local-ttl=300
address=/minecraft.server/192.168.0.116
address=/mc.local/46.53.250.59
address=/ytrechko.server/46.53.250.59
address=/traefik.local/192.168.0.116
address=/jaeger.local/192.168.0.116
address=/prometheus.local/192.168.0.116
address=/grafana.local/46.53.250.59
address=/jmx-exporter.local/46.53.250.59
address=/dnsmasq.local/46.53.250.59
address=/minecraft-local1.duckdns.org/46.53.25059.
address=/minecraft-hamachi.local/25.35.181.13
server=8.8.8.8
server=1.1.1.1